### ISSUE TITLE
Monitor page keeps refreshing

### ISSUE THREAD

**Issue by gabrielyoung92** [mazgch/hpg#19]
I have an issue where the monitor page (https://hpg.mazg.ch/monitor/) keeps refreshing constantly without loading.  Tested this on Chrome, Chrome (Incognito mode), Edge, and Android phone (Chrome) with all the browsers doing the same thing.  Initially, the page loaded fine 

In the attached video the web UI as presented by the module loads and can be refreshed ok.  As soon as "Monitor" is clicked it redirects to the monitor page and just continues to reload.  Even if you load the URL without the "?ip=" it will keep reloading
https://github.com/mazgch/hpg/assets/76025494/8c666195-05f9-4e50-8c57-a9271216ee74

The hardware is a ublox-xplr-hpg-2-gnss-kit

**Comment by mazgch** [comment]
What is page-script.js

Does it happen if there is no device avaialble. Just unpower it.

Can you give me any hint what might be the last thing that done before it reloads, maybe try to break on any exceptions.

**Comment by gabrielyoung92** [comment]
This is the Passkey feature of my Bitwarden password manager.  This issue also occurs in other browsers where I do not use Bitwarden
chrome-extension://nngceckbapebfimnlniiiahkandclblb/content/fido2/page-script.js

I was able to capture the network tab again, it looks like it is trying to load HTTP then gets a redirect to HTTPS
![2](https://github.com/mazgch/hpg/assets/76025494/b4d3ebdd-3250-494c-9f8a-7f8bf8495b0a)
![1](https://github.com/mazgch/hpg/assets/76025494/56b8afbb-0490-496f-b6d1-5ee13431bbf7)

It looks like under hpg/monitor/js/monitor.js Line 38, it is trying to redirect HTTPSback to HTTP, then GitHub reverses it back to HTTPS when serving the page

**Comment by mazgch** [comment]
The https will not work with this page as it will cause issues with mixed content as the websocket on the device is using insecure ws (not wss) connection. You have to use the http://hpg.mazg.ch/monitor/ this is why the page will redirect to http if it was loaded using https protocol. It should stay with http it is not clear to me why it would redirect back to https.

**Comment by mazgch** [comment]
Now a message box will popup before redirecting. Can you confirm that it is wirking with http so we can close this?

**Comment by gabrielyoung92** [comment]
I have just loaded the latest copy of the code onto the module
A popup does appear now but if I click OK it goes into an endless loop
If I click cancel the attached the page loads but freezes.
Please see attached video

https://github.com/mazgch/hpg/assets/76025494/8ed7c7b8-0c2d-4ced-a552-17b9e7ca9ff1

**Comment by mazgch** [comment]
Have you tried to enter http://hpg.mazg.ch/monitor/ manualy ?

**Comment by gabrielyoung92** [comment]
Originally doing that didn't work, but since Chrome has just updated it works now and the page loads.  It does product that message once, clicking ok then manually changing https:// to HTTP:// works.  Thanks

**Comment by mazgch** [comment]
Thanks Gabriel for confirming and sorry for the inconvenience, if you have a proposal/fix how to improve don't hesitate to send me a pull request.
