### ISSUE TITLE
LTE socket error when verifying

### ISSUE THREAD

**Issue by phant0m85** [mazgch/hpg#20]
I am using esp32 2.0.9 with all recommended library versions listed in software.ino. This issue is only with the latest version. I would like to use LTE. Anything I am doing incorrectly? Should I just build it given the listed errors?

In file included from C:\git_repos\mazgch\hpg\software\software.ino:76:
C:\git_repos\mazgch\hpg\software\LTE.h: In member function 'bool LTE::ntripConnect(String)':
C:\git_repos\mazgch\hpg\software\LTE.h:483:22: error: 'socketSetSecure' was not declared in this scope
       LTE_CHECK(6) = socketSetSecure(ntripSocket, proto.equalsIgnoreCase("https"), LTE_SEC_PROFILE_NTRIP);
                      ^~~~~~~~~~~~~~~
C:\git_repos\mazgch\hpg\software\LTE.h:483:22: note: suggested alternative: 'socketConnect'
       LTE_CHECK(6) = socketSetSecure(ntripSocket, proto.equalsIgnoreCase("https"), LTE_SEC_PROFILE_NTRIP);
                      ^~~~~~~~~~~~~~~
                      socketConnect
 
exit status 1
 
Compilation error: 'socketSetSecure' was not declared in this scope

**Comment by mazgch** [comment]
Could you please chevk the Sparkfun SARA-R5 library version. This was recently added in a pull request to SFe library.

**Comment by mazgch** [comment]
https://github.com/sparkfun/SparkFun_u-blox_SARA-R5_Arduino_Library/commit/11cc451de73bfaa79af345b26d6cac0fa0ab6971

**Comment by phant0m85** [comment]
Ah, good catch. I was using Sparkfun SARA-R5 library version 1.1.10. After updating, it now verifies. Thank you very much for the fast reply!
