### ISSUE TITLE
authEnc does not exist in LTE.h#L497

### ISSUE THREAD

**Issue by gabrielyoung92** [mazgch/hpg#21]
https://github.com/mazgch/hpg/blob/7a2fe722670ac1c6a09c0cf14ac9779ea79cfce4/software/LTE.h#L497

When setting the debug level to ARDUHAL_LOG_LEVEL_DEBUG or higher in log.h, the program will fail to compile as authEnc does not exist.  It looks like it should be "auth" 
![2024-05-29_133513](https://github.com/mazgch/hpg/assets/76025494/3589f4bd-4264-4771-9614-1db17df2099d)

**Comment by mazgch** [comment]
Thanks @gabrielyoung92 its fixed seems to be a left over of a previous version that I did not carry over, its fixed.
