### ISSUE TITLE
NTRIP correction over LTE fails, but over WIFI works fine

### ISSUE THREAD

**Issue by gabrielyoung92** [mazgch/hpg#22]
I am having an issue with using NTRIP correction data over LTE where it will perform the ntripConnect() [LTE.h:548] but will not get any data.  This is both true for HTTPS (443) and HTTP (2101).  However correctional data will work fine over WIFI.  I am not using PointPerfect

A difference that can be seen in the attached screenshots 
LTE_HTTPS, The connection debug string shows the server URL without the mount point and doesn't go any further
LTE_HTTP, the URL string is full, and the GET line comes through [LTE.h:497] but then disconnects.  This will then loop and try to connect

The hardware I am using is the C214 dev board - The SIM that is inserted into the LARA-R6 module is confirmed working even with m-centre

![WLAN_HTTPS](https://github.com/mazgch/hpg/assets/76025494/ce014a9b-6777-46a6-a6b8-08e1e7338947)
![WLAN_HTTP](https://github.com/mazgch/hpg/assets/76025494/e0492afc-c2bb-4bb1-af20-868a157d1ef2)
![LTE_HTTPS](https://github.com/mazgch/hpg/assets/76025494/dd6757f2-fcb0-4348-82b5-ef025900c778)
![LTE_HTTP](https://github.com/mazgch/hpg/assets/76025494/d553d502-d0c4-4a62-9f3b-f10c68e958cc)

**Comment by mazgch** [comment]
Are you blanking the password and user names in those screenshots or are they really empty? 

Is there any way I could try this, I must admit I have not tested a lot with LTE as I need to swap SIMs.

**Comment by gabrielyoung92** [comment]
Yes, i have blanked out username/passwords.  There are proper credentials which do work.

To use the source of the NTRIP I am using, you can sign up https://gnss.ga.gov.au/stream
It is a free service here in Australia

The particular source that I am using is  [/MBCH00AUS0]  http://ntrip.data.gnss.ga.gov.au:443/MBCH00AUS0

**Comment by mazgch** [comment]
I just added some debug messages that might give us better clues of what is happening or blocking the code to proceed. Just pull them. I might be able to try it later today when I am home.

**Comment by gabrielyoung92** [comment]
Sorry this took a while, I had an issue where the modem was refusing to register to the network here.  it is now working
I have attached 2x log files where I have also enabled  [Lte.enableAtDebugging]  Both methods act different.  
It looks like I can get HTTP over LTE to work.  Not sure about HTTPS yet

I've done some testing using PUTTY and found that a header is required
[PuttySocket_Failed.txt](https://github.com/user-attachments/files/15507934/PuttySocket_Failed.txt)

I created a socket and put in the host part and now I'm getting data through putty
[PuttySocket_Success.txt](https://github.com/user-attachments/files/15507928/PuttySocket_Success.txt)

I did alter the LTE code a little to try and add the Host header but it doesn't seem to work for me
![2024-05-31_132126](https://github.com/mazgch/hpg/assets/76025494/eaae9a31-d793-4bb4-b311-01ba41940b2b)


=== MCU Serial Output data ===
For HTTP it looks like the socket is opened and data is sent to the server (Lines 33-41) but when the read socket (26.13 Read Socket Data +USORD) is attemped there is never any data ready
[HTTP_Log_Serial.txt](https://github.com/user-attachments/files/15507869/HTTP_Log_Serial.txt)

For HTTPS, line 61 the MCU sends [AT+USOWR=0,242] to the LTE module but gets an error back  (26.11 Write socket data +USOWR) returns an error
[HTTPS_Log_Serial.txt](https://github.com/user-attachments/files/15507870/HTTPS_Log_Serial.txt)
(Serial);]

**Comment by mazgch** [comment]
I pushed some fixes to LTE.h. Seems there was an additional cr/lr missing for this server. At least insecure connection using http and 2101 now works 

```
[  5230][_][LTE.h:753] lteRegistered(): registered 1(home) operator "Swisscom" rssi 27 clock "24/06/01,15:35:49+08"
[  5259][_][LTE.h:890] setState(): state change 4(registered)
[  5294][_][LTE.h:890] setState(): state change 5(online)
[  5517][D][LTE.h:482] ntripConnect(): server "http://ntrip.data.gnss.ga.gov.au:2101"
[  5656][_][GNSS.h:302] onPVT(): 11.9.2022 00:21:48 lat 0.0000000 lon 0.0000000 msl -17.000 fix 0(No) carr 0(No) hacc 4294967.295 source -
[  5923][D][LTE.h:496] ntripConnect(): GET "/MBCH00AUS0" user="username" pwd="password" auth="scrambleduserpwd" ver="Ntrip/2.0"
[  6354][_][LTE.h:535] ntripConnect(): url "http://ntrip.data.gnss.ga.gov.au:2101/MBCH00AUS0" user "username" pwd "password" ver "Ntrip/2.0" connected
[  6368][_][LTE.h:890] setState(): state change 7(ntrip)
[  6431][_][LTE.h:591] ntripTask(): read 111 bytes
[  6510][_][LTE.h:612] ntripTask(): write "$GPGGA,131240.00,0000.0000,N,00000.0000,E,1,31,0.87,453.4,M,47.3,M,,*5C\r\n" 71 bytes
```

I did not get the https/443 version working so far. probably something to to with the TLS negotiation.
 
Here also just for completeness the two curl requests that worked from the console. 
```
~ % curl -v -u username:password -f -v --http0.9 --header "Ntrip-Version: Ntrip/2.0" "https://ntrip.data.gnss.ga.gov.au:443/MBCH00AUS0" 
* Host ntrip.data.gnss.ga.gov.au:443 was resolved.
* IPv6: (none)
* IPv4: 3.104.156.106, 52.65.142.231, 13.237.241.59
*   Trying 3.104.156.106:443...
* Connected to ntrip.data.gnss.ga.gov.au (3.104.156.106) port 443
* ALPN: curl offers h2,http/1.1
* (304) (OUT), TLS handshake, Client hello (1):
*  CAfile: /etc/ssl/cert.pem
*  CApath: none
* (304) (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256 / [blank] / UNDEF
* ALPN: server did not agree on a protocol. Uses default.
* Server certificate:
*  subject: CN=*.prod-data.gnss.ga.gov.au
*  start date: Nov 13 00:00:00 2023 GMT
*  expire date: Dec 12 23:59:59 2024 GMT
*  subjectAltName: host "ntrip.data.gnss.ga.gov.au" matched cert's "*.data.gnss.ga.gov.au"
*  issuer: C=US; O=Amazon; CN=Amazon RSA 2048 M02
*  SSL certificate verify ok.
* using HTTP/1.x
* Server auth using Basic with user 'mazgch'
> GET /MBCH00AUS0 HTTP/1.1
> Host: ntrip.data.gnss.ga.gov.au
> Authorization: Basic bWF6Z2NoOkZvbyFCYXIx
> User-Agent: curl/8.6.0
> Accept: */*
> Ntrip-Version: Ntrip/2.0
> 
< HTTP/1.1 200 OK
< Connection: close
< Content-Type: gnss/data
< Date: Sat, 01 Jun 2024 13:20:08 GMT
< Transfer-Encoding: chunked
< 
Warning: Binary output can mess up your terminal. Use "--output -" to tell 
Warning: curl to output it to your terminal anyway, or consider "--output 
Warning: <FILE>" to save to a file.
* Failure writing output to destination
* Failed reading the chunked-encoded stream
* Closing connection
* TLSv1.2 (OUT), TLS alert, close notify (256):
... ~ % curl -v -u user:password -f -v --http0.9 --header "Ntrip-Version: Ntrip/2.0" "http://ntrip.data.gnss.ga.gov.au:2101/MBCH00AUS0"
* Host ntrip.data.gnss.ga.gov.au:2101 was resolved.
* IPv6: (none)
* IPv4: 3.104.156.106, 52.65.142.231, 13.237.241.59
*   Trying 3.104.156.106:2101...
* Connected to ntrip.data.gnss.ga.gov.au (3.104.156.106) port 2101
* Server auth using Basic with user 'mazgch'
> GET /MBCH00AUS0 HTTP/1.1
> Host: ntrip.data.gnss.ga.gov.au:2101
> Authorization: Basic bWF6Z2NoOkZvbyFCYXIx
> User-Agent: curl/8.6.0
> Accept: */*
> Ntrip-Version: Ntrip/2.0
> 
< HTTP/1.1 200 OK
< Connection: close
< Content-Type: gnss/data
< Date: Sat, 01 Jun 2024 13:21:11 GMT
< Transfer-Encoding: chunked
< 
Warning: Binary output can mess up your terminal. Use "--output -" to tell 
Warning: curl to output it to your terminal anyway, or consider "--output 
Warning: <FILE>" to save to a file.
* Failure writing output to destination
* Failed reading the chunked-encoded stream
* Closing connection

```

**Comment by gabrielyoung92** [comment]
Morning,

ALmost there, I had to add another line to the code to get it to work. Now I am receiving the NTRIP data over LTE and even getting the RTK led to flash on the PCB

![2024-06-03_094144](https://github.com/mazgch/hpg/assets/76025494/cb2ff067-1e6c-49ba-a901-aea83c75718f)

**Comment by mazgch** [comment]
Nice that you got the same solutions.

**Comment by gabrielyoung92** [comment]
Hi Michael,

Yes, we can close this now.  I believe that using the correction data over an unencrypted channel is acceptable as it is already publicly accessible data. Thanks for your help with this.

Gab
