### ISSUE TITLE
Correction source to L-band will never update the keys

### ISSUE THREAD

**Issue by phant0m85** [mazgch/hpg#26]
When I set the correction source to "L-band only," the SPARTN keys never update. I have the wifi set up and assumed it would grab fresh keys when on the local network, but it does not. It only works if I set it to Wifi + L-band or LTE + L-band. Once I pick one of the hybrid methods and then change it back to L-band only, it works until the keys expire. 

![image](https://github.com/user-attachments/assets/be7294d3-9d18-4cd5-b151-e7f7e0ebdb09)

**Comment by mazgch** [comment]
That might be indeed possible, it likely will also not refresh the keys regularly after they expire you would need to change the statemachines in the LTE and WLAN code. You would have to remain subscribed to only the keys topic even in LBAND only configuration. Or you could provide keys externally through a communication interface. 

If you like provide a pull request I will review.

**Comment by phant0m85** [comment]
Can you confirm if the code will or will not update the JSON or keys when connected to local Wi-Fi in **L-band only** correction source mode?

If it does not auto-update json/keys I am not savvy with code and will just need to upload the updated json file every 28-56 days through the web portal or change to hybrid Wifi/LTE + L-band.

**Comment by mazgch** [comment]
Why don't you just leave it at wifi + lband. You have the benefit that keys are updated and while you are wifi connected you even have a more reliable correction stream as lband can be blocked easily.

For me lband only was just added to allow testing and forcing usage of lband corrections. I this os really important for your business and you are wiling to sponser my work I am able to add this feature.

**Comment by phant0m85** [comment]
I was just testing L-band only and did not want to accidentally connect to wifi/ip stream. Thank you for confirming this.
